package domain.notification;

public enum NotificationType {
    INTERVIEW_SCHEDULED,
    INTERVIEW_UPDATED,
    INTERVIEW_CANCELLED,
    INTERVIEW_REMINDER,
    APPLICATION_ACCEPTED,
    APPLICATION_REJECTED
}
